import fs from "node:fs/promises";
import path from "node:path";
import { minify } from "terser";

const inputPath = "src/assets/scripts/authored/header-condense.script.js";
const outputPath = "src/assets/scripts/generated/header-condense.script.ts";

const source = await fs.readFile(inputPath, "utf8");

const result = await minify(source, {
  compress: true,
  mangle: true,
  format: {
    comments: false,
  },
});

const code = result.code ?? source.trim();

const output = `// Generated by scripts/build-scripts.mjs
// Do not edit manually.

export const HEADER_CONDENSE_SCRIPT = ${JSON.stringify(code)};
`;

await fs.mkdir(path.dirname(outputPath), { recursive: true });
await fs.writeFile(outputPath, output);
